services:
  mariadb:
    image: 'mariadb:latest'
    container_name: mariadb
    environment:
      MARIADB_DATABASE: school_db
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: root
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - '9000:80'
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mariadb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/school_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local